const products = [
  {
    id: 1,
    nombre: "Aurora Ring",
    codigo: 78202,
    precio: 125.28,
    categoria: "Anillo",
    imagenes: ["../images/joya1.png"],
    descripcion: "Anillo rodio rosado",
    stock: [
      { color: "rodio rosado", talla: "48", cantidad: 50 },
      { color: "rodio rosado", talla: "50", cantidad: 30 },
    ],
  },
  {
    id: 2,
    nombre: "Blissful Baubles",
    codigo: 78203,
    precio: 268.21,
    categoria: "Anillo",
    imagenes: ["../images/joya1.png"],
    descripcion: "Anillo diamante",
    stock: [
      { color: "dorado", talla: "48", cantidad: 50 },
      { color: "dorado", talla: "50", cantidad: 30 },
      { color: "dorado", talla: "52", cantidad: 45 },
    ],
  },
  {
    id: 3,
    nombre: "Blissful Bloom Ring",
    codigo: 78204,
    precio: 620.73,
    categoria: "Anillo",
    imagenes: ["../images/joya1.png"],
    descripcion: "Anillo de pétalos",
    stock: [
      { color: "dorado", talla: "48", cantidad: 14 },
      { color: "dorado", talla: "50", cantidad: 30 },
      { color: "dorado", talla: "52", cantidad: 35 },
    ],
  },
  {
    id: 4,
    nombre: "Delights Earrings",
    codigo: 78201,
    precio: 327.71,
    categoria: "Aretes",
    imagenes: ["../images/joya1.png"],
    descripcion: "Aretes de delfin corta",
    stock: [{ color: "dorado", cantidad: 44 }],
  },
  {
    id: 5,
    nombre: "Dreamy Infinity Ring",
    codigo: 78215,
    precio: 327.71,
    categoria: "Anillo",
    imagenes: ["../images/joya1.png"],
    descripcion: "Anillo diamante rosa",
    stock: [
      { color: "dorado", talla: "50", cantidad: 30 },
      { color: "dorado", talla: "52", cantidad: 15 },
    ],
  },
  {
    id: 6,
    nombre: "Elegance Earrings",
    codigo: 78206,
    precio: 620.73,
    categoria: "Aretes",
    imagenes: ["../images/joya1.png"],
    descripcion: "Aretes de aro largo",
    stock: [{ color: "dorado", cantidad: 60 }],
  },
  {
    id: 7,
    nombre: "Exquisite Earrings",
    codigo: 92701,
    precio: 125.28,
    categoria: "Aretes",
    imagenes: ["../images/joya1.png"],
    descripcion: "Arete de gota dorado",
    stock: [{ color: "dorado", cantidad: 50 }],
  },
  {
    id: 8,
    nombre: "Exquisite Ornaments",
    codigo: 78210,
    precio: 125.28,
    categoria: "Aretes",
    imagenes: ["../images/joya1.png"],
    descripcion: "Aretes de hojas dorado",
    stock: [{ color: "dorado", cantidad: 69 }],
  },
  {
    id: 9,
    nombre: "Glamour Necklace",
    codigo: 78211,
    precio: 620.73,
    categoria: "Collar",
    imagenes: ["../images/joya1.png"],
    descripcion: "Collar dorado de dijes redondos",
    stock: [{ color: "dorado", cantidad: 30 }],
  },
  {
    id: 10,
    nombre: "Glimmering Ring",
    codigo: 78212,
    precio: 620.73,
    categoria: "Anillo",
    imagenes: ["../images/joya1.png"],
    descripcion: "Anillo dorado de diamantes redondos",
    stock: [
      { color: "dorado", talla: "48", cantidad: 30 },
      { color: "dorado", talla: "50", cantidad: 15 },
      { color: "dorado", talla: "52", cantidad: 30 },
      { color: "dorado", talla: "56", cantidad: 25 },
    ],
  },
  {
    id: 11,
    nombre: "Luxurious Lustre",
    codigo: 78213,
    precio: 110.48,
    categoria: "Aretes",
    imagenes: ["../images/joya1.png"],
    descripcion: "Arete redondo con perlas",
    stock: [{ color: "dorado", cantidad: 48 }],
  },
  {
    id: 12,
    nombre: "Luxury Charms",
    codigo: 78214,
    precio: 327.71,
    categoria: "Anillo",
    imagenes: ["../images/joya1.png"],
    descripcion: "Anillo dorado de abeja",
    stock: [
      { color: "dorado", talla: "52", cantidad: 15 },
      { color: "dorado", talla: "54", cantidad: 30 },
      { color: "dorado", talla: "56", cantidad: 15 },
    ],
  },
  {
    id: 13,
    nombre: "Luxury Charms Ring",
    codigo: 78205,
    precio: 620.73,
    categoria: "Anillo",
    imagenes: ["../images/joya1.png"],
    descripcion: "Anillo dorado con cuarzo",
    stock: [
      { color: "dorado", talla: "48", cantidad: 20 },
      { color: "dorado", talla: "50", cantidad: 25 },
      { color: "dorado", talla: "52", cantidad: 10 },
      { color: "dorado", talla: "56", cantidad: 18 },
      { color: "dorado", talla: "58", cantidad: 14 },
      { color: "dorado", talla: "60", cantidad: 25 },
    ],
  },
  {
    id: 14,
    nombre: "Majestic Mementos",
    codigo: 78216,
    precio: 350.24,
    categoria: "Collar",
    imagenes: ["../images/joya1.png"],
    descripcion: "Collar grande de perlas coloridas",
    stock: [{ color: "dorado", cantidad: 56 }],
  },
  {
    id: 15,
    nombre: "Opulent Jewels Ring",
    codigo: 78217,
    precio: 168.76,
    categoria: "Anillo",
    imagenes: ["../images/joya1.png"],
    descripcion: "Anillo dorado de linea doble",
    stock: [
      { color: "dorado", talla: "48", cantidad: 30 },
      { color: "dorado", talla: "52", cantidad: 15 },
      { color: "dorado", talla: "54", cantidad: 30 },
      { color: "dorado", talla: "58", cantidad: 15 },
    ],
  },
  {
    id: 16,
    nombre: "Radiance Necklace",
    codigo: 78218,
    precio: 168.76,
    categoria: "Collar",
    imagenes: ["../images/joya1.png"],
    descripcion: "Collar doble dorado",
    stock: [{ color: "dorado", cantidad: 67 }],
  },
  {
    id: 17,
    nombre: "Radiant Reflections",
    codigo: 78219,
    precio: 230.71,
    categoria: "Collar",
    imagenes: ["../images/joya1.png"],
    descripcion: "Collar dorado de gotas esmeralda",
    stock: [{ color: "dorado", cantidad: 74 }],
  },
  {
    id: 18,
    nombre: "Reflections Necklace",
    codigo: 78220,
    precio: 620.73,
    categoria: "Collar",
    imagenes: ["../images/joya1.png"],
    descripcion: "Collar tipo serpiete roja con negro",
    stock: [{ color: "dorado", cantidad: 46 }],
  },
  {
    id: 19,
    nombre: "Serene Solitaire Earrings",
    codigo: 78221,
    precio: 125.28,
    categoria: "Aretes",
    imagenes: ["../images/joya1.png"],
    descripcion: "Aretes de corazon azul",
    stock: [{ color: "dorado", cantidad: 23 }],
  },
  {
    id: 20,
    nombre: "Shimmering Stones",
    codigo: 78223,
    precio: 168.76,
    categoria: "Anillo",
    imagenes: ["../images/joya1.png"],
    descripcion: "Anillo dorado de diamantes rosas",
    stock: [
      { color: "dorado", talla: "48", cantidad: 10 },
      { color: "dorado", talla: "52", cantidad: 5 },
      { color: "dorado", talla: "54", cantidad: 33 },
      { color: "dorado", talla: "58", cantidad: 65 },
    ],
  },
  {
    id: 21,
    nombre: "Sparkling Ring",
    codigo: 78224,
    precio: 620.73,
    categoria: "Anillo",
    imagenes: ["../images/joya1.png"],
    descripcion: "Anillo plateado circular",
    stock: [
      { color: "plateado", talla: "48", cantidad: 10 },
      { color: "plateado", talla: "54", cantidad: 15 },
      { color: "plateado", talla: "56", cantidad: 20 },
      { color: "plateado", talla: "58", cantidad: 15 },
    ],
  },
  {
    id: 22,
    nombre: "Timeless Elegance Ring",
    codigo: 78225,
    precio: 168.76,
    categoria: "Anillo",
    imagenes: ["../images/joya1.png"],
    descripcion: "Anillo ancho de perlas azules",
    stock: [
      { color: "dorado", talla: "48", cantidad: 37 },
      { color: "dorado", talla: "54", cantidad: 65 },
    ],
  },
  {
    id: 23,
    nombre: "Timeless Halo Earrings",
    codigo: 78235,
    precio: 620.73,
    categoria: "Aretes",
    imagenes: ["../images/joya1.png"],
    descripcion: "Aretes cuadrados pequeños",
    stock: [{ color: "plateado", cantidad: 38 }],
  },
  {
    id: 24,
    nombre: "Timeless Treasures",
    codigo: 78250,
    precio: 687.7,
    categoria: "Aretes",
    imagenes: ["../images/joya1.png"],
    descripcion: "Aretes Redondos Grabados",
    stock: [{ color: "plateado", cantidad: 50 }],
  },
  {
    id: 25,
    nombre: "Divine Diamonds",
    codigo: 78256,
    precio: 580.85,
    categoria: "Anillo",
    imagenes: ["../images/joya1.png"],
    descripcion: "Anillo diamante blanco con detalles",
    stock: [{ color: "dorado", cantidad: 30 }],
  },
];

const containerCards = document.getElementById("containerCards");

const printProducts = (container, listProducts) => {
    container.innerHTML = "";
    listProducts.forEach(element => {
        container.innerHTML += `
            <article class="card" data-click="card">
                <img src=${element.imagenes[0]} alt=${element.nombre} data-click="card">
                <h3 data-click="card">${element.nombre}</h3>
                <span data-click="card">$${element.precio}</span>
            </article>
        `;
    });
}


printProducts(containerCards, products);

document.addEventListener("click", (event) => {
    
    if (event.target.getAttribute("data-click") === "card") {        
        location.href = "./details.html";
    }
})